media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"synth","tempo":70,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":36};
abc_arr = ["X:1",
"T:Title",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/4",
"Q:1/4=70",
"M:4/4",
"I:linebreak $",
"K:G",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:1",
"!mp! F4- | F2 (3F G A | F3 z/ B,/ | ^C4 | F4- | F2 (3F G A | E3 z/ G/4F/4 | G3 B, ||!mf! [Ff]4- | %9",
" [Ff]2 (3[Ff] [Gg] [Aa] | [Ff]3 z/ [B,B]/ | [^C^c]4 | [Ee]4 | [Ff]2 [Gg] [Aa] | [Bb]3 z/ [cc']/ | %15",
" [Bb]2 [^c^c']2 || [Ff]4- | [Ff]2 (3f g a | f4 | g3 a | b4 | z2 (3b c' d' | b2 ^c'2 | d'4 || %24",
"\"^cresc.\" [ae']2 (3A B c | B2 G2 | [Gc]2 (3c d e | d4 | !>![EGce]4 |!>(! F/G/A/B/ e/f/g/b/ | %30",
" [gbe']4!>)! |] %31",
"V:2",
" E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | %4",
" E,,B,,E,F, G,B,G,F, | D,,A,,E,F, G,B,G,F, | C,,G,,E,F, G,B,G,F, | C,,G,,E,G, CG, D,,2 || %8",
" E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | E,,B,,E,F, G,B,G,F, | %12",
" C,,G,,C,D, E,G,E,D, | D,F,G,B, G,B,G,F, | =F,,C,=F,A, C=FCA, | G,,D,G,B, ^CA,E,A,, || %16",
" E,,G,,B,,E, F,E,B,,G,, | C,,G,,C,E, F,E,C,G,, | A,,,A,,C,E, F,E,C,A,, | G,,,G,,B,,E, F,E,B,,F,, | %20",
" E,,B,,E,G, F,E,B,,G,, | C,,G,,C,E, G,E,C,G,, | A,,,A,,C,E, F,E,C,A,, | G,,,G,,B,,E, G,E, B,,2 || %24",
" =F,,C,=F,A, C=FCA, | G,,D,G,B, E4 | [=F,,A,,]C,=F,A, C=FCA, | ^A,,^E,,D,^E, ^A,E,D,A,, | %28",
" C,,G,,C,E, G,E, C,2 | E,B, E6 | z8 |] %31",
""];
