media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":62,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":38};
abc_arr = ["X:1",
"T:Étude No. 22 in D Major",
"C:Stephen Heller(1815–1888)",
"Z:Heller István",
"%%measurenb 0",
"%%score { ( 1 2 ) | 3 }",
"L:1/8",
"Q:1/4=62",
"M:2/4",
"I:linebreak $",
"K:D",
"V:1 treble nm=\"Piano\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/16",
"V:2 treble ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:3 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"!p! z2[I:staff +1] (F,A,DF)[I:staff -1] x2 | z2[I:staff +1] (F,B,DF)[I:staff -1] x2 | %2",
" z2[I:staff +1] (F,A,DF)[I:staff -1] x2 | z2 (CEAc) x2 | z2!<(! (DGBd)!<)! x2 | %5",
" z2!<(! (B,DGB)!<)! x2 | z2 (_B,DG_B) x2 | z2 (A,CEA) x2 | z2[I:staff +1] (F,A,DF)[I:staff -1] x2 | %9",
" z2[I:staff +1] (F,B,DF)[I:staff -1] x2 | z2[I:staff +1] (=F,B,D=F)[I:staff -1] x2 | %11",
" z2[I:staff +1] (E,A,CE)[I:staff -1] x2 | z2 (A,CFA) x2 | z2 (A,B,^DA) x2 | z2 (^G,=DE^G) x2 | %15",
" z2 (=G,A,C=G) x2 | z2 (A,DFA) x2 | z2\"_cresc.\" (G,A,CG) x2 | z2 (A,DFA) x2 | z2 (B,DEB) x2 | %20",
" z2 (CEGc)!f! x2 | z2 (EGAe) x2 | z2 (DFAc) x2 | z2[I:staff +1] (E,_B,DE)[I:staff -1] x2 | %24",
" z2[I:staff +1] (D,F,A,D)[I:staff -1] x2 | z2[I:staff +1] (F,A,^DF)[I:staff -1] x2 | %26",
" z2[I:staff +1] (^G,B,=D^G)[I:staff -1] x2 | z2[I:staff +1] (=G,CE=G)\"^\"[I:staff -1] x2 | %28",
" z2[I:staff +1] (F,A,DF)[I:staff -1] x2 | z2[I:staff +1] (F,B,DF)[I:staff -1] x2 | %30",
" z2[I:staff +1] (F,A,DF)[I:staff -1] x2 | z2 (CEAc) x2 | z2 (DGBd) x2 | z2 (B,DGB) x2 | %34",
" z2 (_B,DG_B) x2 | z2 (A,CEA) x2 |!p! d4 z4 |] %37",
"V:2",
" x4 | x4 | x4 | x4 | x4 | x4 | x4 | x4 | x4 | B3 x | ^G3 x | e3 x | x4 | a3 x | f3 x | e3 x | %16",
" A3 x | c3 x | A3 x | e3 x | c3 x | a3 x | f3 x | d3 x | A3 x | =c3 x | B3 x | c3 x | a3 x | x4 | %30",
" x4 | x4 | x4 | x4 | x4 | x4 | x4 |] %37",
"V:3",
"!ped! (D,,/D,/) z z[I:staff -1] A!ped-up! |!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] B!ped-up! | %2",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] A!ped-up! | %3",
"!ped![I:staff +1] (A,,/A,/) z z[I:staff -1] e!ped-up! | %4",
"!ped![I:staff +1] (A,,/B,/) z z[I:staff -1] g!ped-up! | %5",
"!ped![I:staff +1] (A,,/G,/) z z[I:staff -1] e!ped-up! | %6",
"!ped![I:staff +1] (A,,/G,/) z z\"^dim.\"[I:staff -1] d!ped-up! | %7",
"!ped![I:staff +1] (A,,/G,/) z z[I:staff -1] c!ped-up! | %8",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] A!ped-up! | %9",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] A!ped-up! | %10",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] =f!ped-up! | %11",
"!ped![I:staff +1] (C,,/C,/) z z[I:staff -1] A!ped-up! | %12",
"!ped![I:staff +1] (F,,/F,/) z z\"^\"[I:staff -1] c!ped-up! | %13",
"!ped![I:staff +1] (F,,/F,/) z z[I:staff -1] ^d!ped-up! | %14",
"!ped![I:staff +1] (E,,/E,/) z z[I:staff -1] e!ped-up! | %15",
"!ped![I:staff +1] (A,,/E,/) z z[I:staff -1] A!ped-up! | %16",
"!ped![I:staff +1] (D,,/A,,/) z z[I:staff -1] d!ped-up! | %17",
"!ped![I:staff +1] (E,,/A,,/) z z[I:staff -1] B!ped-up! | %18",
"!ped![I:staff +1] (F,,/D,/) z z[I:staff -1] f!ped-up! | %19",
"!ped![I:staff +1] (G,,/D,/) z z[I:staff -1] d!ped-up! | %20",
"!ped![I:staff +1] (A,,/E,/) z z[I:staff -1] b!ped-up! | %21",
"!ped![I:staff +1] (C,/A,/) z z[I:staff -1] g!ped-up! | %22",
"!ped![I:staff +1] (D,/A,/) z z[I:staff -1] d!ped-up! | %23",
"!ped![I:staff +1] (G,,/D,/) z z[I:staff -1] _B!ped-up! | %24",
"!ped![I:staff +1] (A,,,/A,,/) z z[I:staff -1] F!ped-up! | %25",
"!ped![I:staff +1] (A,,,/A,,/) z z[I:staff -1] B!ped-up! | %26",
"!ped![I:staff +1] (A,,,/A,,/) z z[I:staff -1] e!ped-up! | %27",
"!ped![I:staff +1] (A,,,/A,,/) z z[I:staff -1] a!ped-up! | %28",
"!ped![I:staff +1] (D,,/A,,/D,) z[I:staff -1] d!ped-up! | %29",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] B!ped-up! | %30",
"!ped![I:staff +1] (D,,/D,/) z z[I:staff -1] A!ped-up! | %31",
"!ped![I:staff +1] (A,,/A,/) z z[I:staff -1] e!ped-up! | %32",
"!ped![I:staff +1] (A,,/A,/) z z[I:staff -1] g!ped-up! | %33",
"!ped![I:staff +1] (A,,/G,/) z z[I:staff -1] e!ped-up! | %34",
"!ped![I:staff +1] (A,,/G,/) z z\"^dim.\"[I:staff -1] d!ped-up! | %35",
"!ped![I:staff +1] (A,,/G,/) z z[I:staff -1] c!ped-up! |[I:staff +1] [D,,D,]2 z2 |] %37",
""];
