media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":72,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":35};
abc_arr = ["X:1",
"T:Gensokyo",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/4=72",
"M:4/4",
"I:linebreak $",
"K:F",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 1",
"%%MIDI control 7 110.000034",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 1",
"%%MIDI control 7 110.000034",
"%%MIDI control 10 63.5",
"V:1",
" [Dd]4 (3[Aa]2 [Gg]2 [Ff]2 | [Ee]4 z [Cc] [A,A]2 | [DFAd]2 [fa]A [eg]A [df]2 | z Bdf eGce | %4",
" [Adf]4 (3[Adf]2 g2 a2 | [Acea]4 (3[Aa]2 [=B=b]2 [cc']2 | [cfac']2 [cf=b]2 [cfa]2 [cfc']2 | %7",
" [ead']4 [ea^c']3 a/=c'/ | (3[fd']2 [fa]2 g2 (3[ceg]2 [cf]2 [ceg]2 | [FAd]4 (3[FAd]2 e2 f2 | %10",
" [FBf]2 [FBe]2 [FBd]2 [FBc]2 | [EAd]4 [EA^ce]3 a/c'/ | (3[fd']2 [fa]2 g2 (3[ceg]2 [cf]2 [ceg]2 | %13",
" [FAd]4 (3[FAd]2 e2 f2 | (3[FBdf]2 [Gg]2 [Aa]2 (3[Aa]2 [=B=b]2 [cc']2 | %15",
" [Ba^c']2 [dad']2 [eac'e'][fa][fa][f=c'] | [dfd']3 c'/d'/ c'agc' | [dfa]2 de [Adf][fa][fa][fc'] | %18",
" [fbd']3 c'/d'/ [gf'](3e'/d'/e'/ d'c' | d'Adg [Ad^f]c'/d'/ c'a | g4 [ce]c'/d'/ c'g | %21",
" f2 de [Adf]dde | [Bdf]3 g [Gce]3 d | [D^FAd]4 z dde | [Bdf]3 [Bg] [Gce]>[Gceg]- [Gceg][egc'] | %25",
" [d^fad']8 |] %26",
"V:2",
" D,,A,,D,F, A,DFA, | C,,G,,C,E, G,,C, G,,2 | B,,,F,,B,,D, F,B, D2 | %3",
" B,,,F,,[B,,D,]F,, C,,G,,[C,E,]G,, | D,,A,,D,F, A,DFA, | A,,,E,,A,,C, E,A, CE, | F,,C,F,A, CFAC | %7",
" A,,E,A,D ^CA,F,A,, | (3[B,,D,F,B,]2 [B,,D,F,B,]2 [B,,D,F,B,]2 (3[C,E,G,C]2 [C,E,G,C]2 [C,E,G,C]2 | %9",
" D,F,A,D- DF, [A,D]2 | B,,F,B,D- DF,DB, | A,,E,A,D ^CA,F,A,, | %12",
" (3[B,,D,F,B,]2 [B,,D,F,B,]2 [B,,D,F,B,]2 (3[C,E,G,C]2 [C,E,G,C]2 [C,E,G,C]2 | %13",
" D,F,A,D- DF, [A,D]2 | B,,G,B,D- DF, [B,D]2 | [A,,^C,E,A,]2 [A,,C,E,A,]A,, [A,,C,E,A,]2 A,,A,,, | %16",
" [B,,,B,,]B,, [F,B,]2 [C,,C,]C,[G,C]E, | [D,,D,]D,F,D, [D,,D,]D,F,D, | %18",
" B,,,F,,[B,,D,]F,, C,,G,,[C,E,]G,, | D,,A,,[D,^F,]A,, D,,A,,[D,F,]A,, | %20",
" B,,,F,,[B,,D,]F,, C,,G,,[C,E,]G,, | D,,A,,[D,F,]A,, D,,A,, [D,F,]2 | %22",
" [B,,,F,,B,,]>[B,,,F,,B,,] z/ B,,,/[F,,B,,] C,,G,, C,2 | D,,A,,D,^F, A,2 z2 | %24",
" [B,,,F,,B,,]>[B,,,F,,B,,] z/ B,,,/[F,,B,,] [C,,G,,C,]>[C,,G,,C,]- [C,,G,,C,][C,,G,,C,] | %25",
" D,,A,,D,^F, A,D ^F2 |] %26",
""];
