media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":4,"extract":1,"portsel":"synth","tempo":110,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":30};
abc_arr = ["X:1",
"T:Kasss Theme",
"Z:Nintendo 2017",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/4",
"Q:1/4=110",
"M:3/4",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
" z E2 E/_E/ =Ec | B6 | z E2 E/_E/ =EB | A6 | z A BA [^ce][eg] | .[df]2 z .[df] [df]2 | %6",
" .[df]2 .[eg]2 .[df]2 | .[df]2 [ce]4 | z2 z c de | [ce]3 [_Bd] [Bd]2- | [Bd]2 z d ed | %11",
" [Bd]3 [Ac] [Ac]2- | [Ac]4 AB | c3 d c2 | .B2 .e2 .c2 | A6- | A E2 E/_E/ =Ec | B6 | %18",
" z E2 E/_E/ =EB | A6 | z A BA [^ce][eg] | .[df]2 z .[df] .[df] z | .[df]2 .[eg]2 .[df]2 | %23",
" .[df]2 [ce]4 | z2 z c de | [ce]3 [_Bd] [Bd]2- | [Bd]2 z d ed | [Bd]3 [Ac] [Ac]2- | [Ac]4 AB | %29",
" c3 d c2 | .B2 .e2 .c2 | A6- | A z4 z |] %33",
"V:2",
" z2 z | B,, .[D,F,A,] [D,F,A,] | E,, .[D,E,^G,] .[D,E,G,] | A,, .[C,E,A,] [C,E,A,] | %4",
" A,, .[^C,G,A,] [C,G,A,] | D,, .[A,,D,F,] [A,,D,F,] | G,, .[B,,D,F,] [B,,G,B,] | %7",
" C,, .[C,E,G,] .[C,E,G,] | C,, .[C,E,G,] .[C,E,G,] | _B,, .[B,,D,F,] .[B,,D,F,] | %10",
" _B,, .[B,,D,F,] .B,, | A,, .[C,E,] .[C,E,] | G,, .[C,E,] .[C,E,] | [C,F,]2 .[C,F,] | .[B,,E,] z2 | %15",
" (A,, E, C, | .A,,) z2 | B,, .[D,F,A,] [D,F,A,] | E,, .[D,E,^G,] .[D,E,G,] | %19",
" A,, .[C,E,A,] .[C,E,A,] | A,, .[^C,G,A,] .[C,G,A,] | D,, .[A,,D,F,] .[A,,D,F,] | %22",
" G,, .[B,,D,F,] .[B,,G,B,] | C,, .[C,E,G,] .[C,E,G,] | C,, .[C,E,G,] [C,E,G,] | %25",
" _B,, .[B,,D,F,] .[B,,D,F,] | _B,, .[B,,D,F,] .B,, | A,, .[C,E,] .[C,E,] | G,, .[C,E,] .[C,E,] | %29",
" [C,F,]2 .[C,F,] | .[B,,E,] z2 | (A,, E, C, | .A,,/) z2 z/ |] %33",
""];
