media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":70,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":38};
abc_arr = ["X:1",
"T:Kira",
"C:Yugo Kanno",
"Z:arr. Carter Smith",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/4=70",
"M:4/4",
"I:linebreak $",
"K:G",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 treble ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"!mp! .[Ace] z .[Ace] z .[ABe] z .[ABe] z | .[Ace] z .[ABe] z z4 | %2",
" .[Ace] z .[Ace] z .[^GBe] z .[GBe] z | .[Ace] z .[^GBe] z z4 | %4",
" .[Ace] z .[Ace] z .[Ace] z .[Ace]!tenuto![Ace] | .[Ace] z .[Ace] z .[Ace] z [Ace]!tenuto![Ace] | %6",
" .[^GBe] z .[GBe] z .[GBe] z .[GBe]!tenuto![GBe] | %7",
" .[^GBe] z .[GBe] z .[GBe] z .[GBe]!tenuto![GBe] | .[Ace] z .[Ace] z .[Ace] z .[Ace]!tenuto![Ace] | %9",
" .[Ace] z .[Ace] z .[Ace] z .[Ace]!tenuto![Ace] | .[Be] z .[Be] z .[Be] z .[^GBe]!tenuto![GBe] | %11",
" .[^GBe] z .[GBe] z .[GBe] z .[GBe] z |!mf!!<(!!8va(! d'3 d'/d'/ d'c'/b/ d'c'/b/ | %13",
" ^a3 a/a/ a^g/=g/ a^g/=g/!<)! |!>(! f4 ^e4 | e6 z2!8va)!!>)! | %16",
"!mp! .[Ace] z .[Ace] z .[ABe] z .[ABe] z | .[Ace] z .[ABe] z z4 | %18",
" .[Ace] z .[Ace] z .[^GBe] z .[GBe] z | .[Ace] z .[^GBe] z z4 | %20",
"!8va(! [dd']3 [dd'] (3[dd'][cc'][Bb] (3[dd'][cc'][Bb] | %21",
" [^A^a]3 [Aa] (3[Aa][^G^g][=G=g] (3[Aa][^G^g][=G=g] | [Ff]4 [^E^e]4 | [Ge]4!8va)! z4 | z8 | z8 | %26",
" z8 | z8 |] %28",
"V:2",
" z8 | z8 | z8 | z8 | z2!mf! A,2 B,2 C2 | F2 GF/G/ F2 E2 | ^D6 E2 | B,8 | z2 A,2 B,2 C2 | %9",
" F2 E2 F2 G2 | ^G6 z E/^E/ | =E6 z2 | .[df] z .[df] z .[df] z .[df]!tenuto![df] | %13",
" .[^Ad] z .[Ad] z .[Ad] z .[Ad]!tenuto![Ad] | .[^A^d] z .[Ad] z .[Ad] z .[Ad]!tenuto![Ad] | %15",
" .c z .[ce] z .[ce] z z2 | z8 |[K:bass] z4 z .A, E,2 | .A,, z z2 z4 | z8 | %20",
"!ff! [B,,B,]2 [D,F,]2 [F,,F,]2 [D,F,]2 | [G,,G,]2 [D,^A,]2 [D,,D,]2 [D,A,]2 | %22",
" [^A,,^A,]2 [^D,A,]2 [F,,F,]2 [D,A,]2 | [E,,C,E,]4 z4 |!p! .A,, z .[A,C] z .E, z .[^G,C] z | %25",
" .A,,.[A,C].E,.[^G,C] z2 z E,, | .A,, z .[A,C] z .E, z .[^G,C] z | .A,,.[A,C].E,.[^G,C] z4 |] %28",
""];
