media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":106,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":36,"drpuse":false};
abc_arr = ["X:1",
"T:III. Laideronnette, Imperatrice des pagodes",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/4",
"Q:1/4=106",
"M:4/4",
"I:linebreak $",
"K:F#",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:2 treble ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
" z2 z2 z4 |\"_m.d\" [GA]4 z4 | [cd]4 z4 | [GA]4 z4 | [cd]4 z4 | z8 | z8 | z8 | %8",
"!pp! (f'd'c'd' a2 f'c') | .d'2 .d'2 (f'd'c'd' | ad'f'c' .d'2) (f'd' | c'd'ac' gafg | %12",
" .d2) (ga c'd'ga | .d2) (fg ac'fg | .d2) (df gadg | .f2) .f2 (f'd'c'd' | a2 f'c' .d'2) .d'2 | %17",
" (f'd'c'd' ad'f'c' | .d'2) (f'd'!<(! c'd'ac' | gafg dfcd!<)! |!mf! A2)!>(! (df gadf | %21",
" .A2) (cd fgcd | .A2) (Ac dfA!>)!d |!f! .c2) [gc']2 z2 [gc']2 | %24",
"!p!!8va(! z (!1![c''d'']!2!!3![f''g''][c''d''] [f''g''][c''d''][f''g''][c''d''])!8va)! | %25",
"!f! z2 [gc']2 z2 [gc']2 | %26",
"!p!!8va(! z (!1![c''d'']!2!!3![f''g''][c''d''] [f''g''][c''d''][f''g''][c''d''])!8va)! | %27",
"!f! z2!>(! [gc']2 z2 [gc']2 | z2 c2 z2 c2 | z8 | z8!>)! | z8 |] %32",
"V:2",
" z2!pp! C D- | D2 F G- | G2 C D- | D2 F G- | G2 (C [DGA] | F [Gcd] A [cd]) | (C [DGA] F [Gcd] | %7",
" A [cd]) (C [DGA] | F [Gcd] A [cd]) | (C [DGA] F [Gcd] | A [cd]) (C [DGA] | F [Gcd] A [cd]) | %12",
" (C B [FG] D) | (C B [FG] D) | (C B [FG] D) | (C [DGA] F [Gcd] | A [cd]) (C [DGA] | %17",
" F [Gcd] A [cd]) | (C [DGA] F [Gcd] | A c) (C D) | (G, F [CD] A,) | (G, F [CD] A,) | %22",
" (G, F [CD] A,) | [CG] !>!c [CG] !>!c | [B,F] B [B,F] B | [CG] !>!c [CG] !>!c | [B,F] B [B,F] B | %27",
" [CG] !>!c [CG] !>!c | C !>!G C !>!G | C G C G | C G C G | C4 |] %32",
""];
