media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":68,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":38};
abc_arr = ["X:1",
"T:The Moldau",
"C:Bedřich Smetana",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/8=136",
"M:6/8",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"\"_cresc.\" [Ge]2 ^f [Bg]2 a | [gb]3 [gb]3 |!f! [ec']3 [ec']2 c' | [db]3 [db]db | %4",
"!>(! [ce^fa]3 [cefa]2 [cefa]!>)! | [Beg]3 [Beg]2 [Beg] | [A^d^f]3 [Adf]3 |!mp! [GBe]4- [GBe]B | %8",
"\"_cresc.\" eG^f [Bg]2 [ca] | [eb]3 [eb]3 |!f! [ec']3 [ec']2 [ec'] |!>(! [db]3 Bdb!>)! | %12",
"!>(! [ca]3 [ce^f]2 a!>)! | [Beg]3/2a3/2 [Bg]3/2[Bg]3/2 | [Ace^f]3 [A^df]3 |!mp! [Ge]4- [Ge]G | %16",
"!<(! [Ec]3/2d3/2 [Gce]2 ^f!<)! | [dg]2 a [gb]2 c' |!>(! [^fd']3 adc'!>)! | [gb]3 B/d/b/g/d/B/ | %20",
" [Ec]2!<(! d [ce]3/2^f3/2!<)! | [Bg]3/2a3/2 b3/2c'3/2 | [^db]3!>(! ^f2 a!>)! | [Bg]3 GBg | %24",
" [^Ag]3 e2 g | [B^db]3 ^f2 f | [^Ag]3 e2 g | [B^db]3 ^f2 f | [Bb]3 ^f2 f |!>(! (B^fb) (Aef)!>)! | %30",
" (GBe) (^Fe^d) | e6 |] %32",
"V:2",
"!ped! (E,B,E ^FEB,)!ped-up! |!ped! (E,G,B, E,G,B,)!ped-up! |!ped! (C,G,C ECG,)!ped-up! | %3",
"!ped! (G,,D,G, B,3)!ped-up! |!ped! (A,,E,^F, A,F,E,)!ped-up! |!ped! (B,,G,B,- B,G,B,)!ped-up! | %6",
"!ped! (B,,^F,B, F,B,,F,)!ped-up! |!ped! (E,,B,,E, E, B,2)!ped-up! |!ped! (E,B,E ^FEB,)!ped-up! | %9",
"!ped! (E,B,E ^FEB,)!ped-up! |!ped! (C,G,E G,C,G,)!ped-up! |!ped! (G,,D,B, D3)!ped-up! | %12",
"!ped! (A,,E,^F, A,F,A,)!ped-up! |!ped! (B,,E,G, B,G,E,)!ped-up! | %14",
"!ped! (A,,C,^F, B,,^D,F,)!ped-up! |!ped! (E,,B,,E, G,3)!ped-up! |!ped! (C,G,C ECG,)!ped-up! | %17",
"!ped! (B,,G,B, DB,G,)!ped-up! |!ped! (A,,^F,A, D A,2)!ped-up! |!ped! (G,,D,B,- B,2 B,)!ped-up! | %20",
"!ped! (A,,E,A, CA,E,)!ped-up! |!ped! (E,B,E ^FEB,)!ped-up! |!ped! (B,,^F,B, ^DB,F,)!ped-up! | %23",
"!ped! (E,B,E- E2 B,)!ped-up! |!ped! (^A,,E,G, ^A,G,E,)!ped-up! |!ped! (B,,^F,B, ^D B,2)!ped-up! | %26",
"!ped! (^A,,E,G, ^A,G,E,)!ped-up! |!ped! (B,,^F,B, F,B,F,)!ped-up! | %28",
"!ped! (B,,^F,B, F, B,2)!ped-up! |!ped! [B,^F]3 A,3!ped-up! |!ped! G,3 ^F,3!ped-up! | [E,,,E,,]6 |] %32",
""];
