media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":80,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":32};
abc_arr = ["X:1",
"T:Naru, Embracing the Light",
"C:Gareth Coker",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/4",
"Q:1/4=80",
"M:3/4",
"I:linebreak $",
"K:D",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:1",
"!mf! d' f e/f/ | g7/4 g/4 a/g/ | f2 A,/D/ | A G F | f2 e/f/ | g2 a/b/ | a3 | z2!8va(! b/c'/ | %8",
" d'2 e'/f'/ | e'/4f'/4e'/ d' c' | b2 c'/d'/ | a3!8va)! | g2 a | b2 g | e2 a | d3 | z A/B/ d- | %17",
" d e f | [da]3- | [da]2 d- | d A/B/ d/e/- | e d e | f3 | a3 | z A/B/ d | e d e | f3/2 g/ a | d2 a | %28",
" z A/B/ d | e d c | d3 | .d' z2 |] %32",
"V:2",
"!ped! D,A, DA, DA,!ped-up! |!ped! B,,A, DA, DA,!ped-up! |!ped! D,A, DA, F,E,!ped-up! | %3",
"!ped! D,A, DA, DA,!ped-up! |\"_sim.\" D,A, DA, DA, | B,,A, DA, DA, | D,A, DA, DA, | D,A, DA, DA, | %8",
" B,,F, B,F, DF, | F,,D, A,D, A,D, | G,,D, G,D, B,D, | D,,A,, D,A,, D,A,, | G,,D, G,D, G,D, | %13",
" E,,B,, G,B,, G,B,, | A,,E, A,E, A,E, | D,,6 | [G,,G,]A, DA, G,A, | [A,,A,]A, DA, G,A, | %18",
" [B,,B,]A, DA, G,A, | [F,,F,]A, DA, G,A, | [G,,G,]A, DA, G,A, | [A,,A,]A, DA, G,A, | %22",
" [D,D]A, DA, G,A, | [D,D]A, DA, G,A, | G,,D, G,A, B,G, | A,,E, A,B, CA, | B,,F, B,C DA, | %27",
" DA, DA, G,A, | G,,D, G,A, B,G, | A,,E, A,B, CA, | DA, DA, G,A, | .D,2 z4 |] %32",
""];
