media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":70,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":40};
abc_arr = ["X:1",
"T:Sechs kleine Präludien",
"C:Johann Sebastian Bach",
"Z:OpenScore (CC0)",
"%%measurenb 0",
"%%score { ( 1 2 ) | 3 }",
"L:1/8",
"Q:1/4=70",
"M:3/4",
"I:linebreak $",
"K:Eb",
"V:1 treble nm=\"Harpsichord\" snm=\"Hch.\"",
"%%MIDI channel 2",
"%%MIDI program 6",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 treble ",
"%%MIDI program 6",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:3 bass ",
"%%MIDI channel 2",
"%%MIDI program 6",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/4",
"V:1",
" cdeGdF | EDCEGc | Fedfac | =B=AGBdf | ecGc=ec | fcgc_ac | dBFBdB | eBfBgB | cAGAce | BGFGBe | %10",
" AGFGAE | DEFDB,A, | G,B,EB,G,B, | A,EB,ECE | B,ECE_DE | C2 E2 A2- | A2 F2 =d2- | d2 B2 g2- | %18",
" gfedcd | e6 | gabgbf | =e=dcegb | af_dg=ec | BGAcf=A | B=df_agf | gedc=Bf | edce=AG | ^FG=AFDA | %28",
" dG^FcBG | C^FG=AEC | B,D^FG=A,F | G2 (B4 | B)_d=ecgB | _ABcAF=E | FA=BGdF | _EFGEC=B, | CE^FD=AC | %37",
" =B,D=F_AG=B | dfecG=B | c6 |] %40",
"V:2",
" x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | %19",
" z B G4 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x6 | x2 A4 | x6 | x6 | x6 | x6 | x6 | %37",
" x6 | x6 | z G E4 |] %40",
"V:3",
" C, C G, | A, A,, z | A, F, D, | G, G,, z | C, C _B, | _A, G, F, | B,, B, A, | G, F, E, | A, C F, | %9",
" G, B, E, | F, A, F, | B, B,, D, | E, E,, _D, | C, B,, A,, | G,, F,, E,, | A,,/E,/A,/G,/F,/E,/ | %16",
" =D,/F,/B,/A,/G,/F,/ | G,/B,/E/_D/C/B,/ | A, B, B,, | E,3/2 B,/ E | E, E _D | C =E, C, | %22",
" F, B,, C, | F,, F, _E, | =D, B,, D, | E, E D | C =A, C | D D, C, | B,, =A,, G,, | E, D, C, | %30",
" D, C, D, | G,,/D,/G,/B,/_D/=F,/ | =E, C, E, | F,/G,/ _A, z | =B,, G,, B,, | C,/D,/ _E, z | %36",
" ^F,, D,, F,, | G,, D, E, | _A,, F,, G,, | C,3/2 G,/ C |] %40",
""];
