media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":90,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":38};
abc_arr = ["X:1",
"T:Pruit Igoe",
"C:Philip Glass",
"Z:Arranged by GhostOfAdelaide",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/8=180",
"M:8/8",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"\"^1\"!p! E8- | E8 |[M:9/8]\"^2\" (A,CEC) (A,CE) (A,C) | (A,CFC) (A,CF) (A,C) | (A,CEC) (A,CE) (A,C) | %5",
"[M:8/8] (A,C_EC)(A,CEC) | (A,C_EC)(A,CEC) | =E8- |[M:12/8] E12 | %9",
"[M:9/8]\"^3\"!mf! (AGFE) (DEF) (A^G) | (AFED) (B,CD) (A^G) | (AEDC) (_B,CD) (A^G) | %12",
"[M:7/8] A=GFE DC_B, | A, z z E DC_B, |[M:8/8]!mp! E8- |[M:12/8] E12 | %16",
"[M:9/8]\"^4\" (A,CEC) (A,CE) (A,C) | (A,CFC) (A,CF) (A,C) | (A,C^FC) (A,CF) (A,C) | %19",
"[M:8/8] (A,_E^FE)(A,EFE) | (A,_E^FE)(A,EFE) | =E8- | E8- |[M:12/8] E12 |] %24",
"V:2",
"!ped! (A,,E,A,E,)(A,,E,A,E,) | (A,,E,A,E,)(A,,E,A,E,)!ped-up! | %2",
"[M:9/8]!ped! (A,,E,A,E,) (A,,E,A,) (A,,E,)!ped-up! |!ped! (A,,F,A,F,) (A,,F,A,) (A,,F,)!ped-up! | %4",
"!ped! (A,,E,A,E,) (A,,E,A,) (A,,E,)!ped-up! |[M:8/8]!ped! (A,,_E,A,E,)(A,,E,A,E,) | %6",
" (A,,_E,A,E,)(A,,E,A,E,)!ped-up! |!ped! (A,,=E,A,E,)(A,,E,A,E,) | %8",
"[M:12/8] (A,,E,A,) (A,,E,A,) (A,,E,A,) (A,,E,A,)!ped-up! |[M:9/8] (A,G,F,E,) (D,E,F,) (A,^G,) | %10",
" (A,F,E,D,) (B,,C,D,) (A,^G,) | (A,E,D,C,) (_B,,C,D,) (A,^G,) |[M:7/8] A,=G,F,E, D,C,_B,, | %13",
" A,,G,F,E, D,C,_B,, |[M:8/8]!ped! (A,,E,A,E,)(A,,E,A,E,) | %15",
"[M:12/8] (A,,E,A,) (A,,E,A,) (A,,E,A,) (A,,E,A,)!ped-up! | %16",
"[M:9/8]!ped! (A,,E,A,E,) (A,,E,A,) (A,,E,)!ped-up! |!ped! (A,,F,A,F,) (A,,F,A,) (A,,F,)!ped-up! | %18",
"!ped! (A,,^F,A,F,) (A,,F,A,) (A,,F,)!ped-up! |[M:8/8]!ped! (A,,^F,A,F,)(A,,F,A,F,) | %20",
" (A,,^F,A,F,)(A,,F,A,F,)!ped-up! |!ped! (A,,=E,A,E,)(A,,E,A,E,) | (A,,E,A,E,)(A,,E,A,E,) | %23",
"[M:12/8]!>(! (A,,E,A,) (A,,E,A,) (A,,E,A,) (A,,E,A,)!ped-up!!>)! |] %24",
""];
