media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":100,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":36};
abc_arr = ["X:1",
"T:Radetzky-Marsch",
"C:Johann Strauss I",
"Z:Public Domain",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/4",
"Q:1/4=100",
"M:4/4",
"I:linebreak $",
"K:D",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"!ff! [Fd][Fd][Fd] z [Fd][Fd][Fd] z | .f2 .e2 (d3 .c) | (B^ABc .d2) .[^Ge]2 | .=A2 z2 z2!p! .f.^e | %4",
" .f z .f.^e .f z .f.e | .f z .=e z .d z .f.^e | .f z .f.^e .f z .f.e | .f z .b z .a z .a.f | %8",
" .^g z .f' z !>!e'4 | .f z .e' z !>!d'4 | !>!c'3 b a=gfe | d2 [Fd]2 [Fd]2 .d'.c' | %12",
" .d' z .d'.c' .d' z .d'.c' | .d' z .g' z .b z .d'.c' | .d' z .d'.c' .d' z .d'.c' | %15",
" .d' z .f' z .a z .[fa] z | (!>![fa]4 .[eg]) z .[gb] z | (!>![gb]4 .[fa]) z .[fd'] z | %18",
" .[ac'] z ([ac'][gb] [fa]) z .[eg] z | .[gb] z ([gb][fa] [eg]) z .[df] z | %20",
" (!>![fa]4 .[eg]) z .[gb] z | (!>![gb]4 .[fa]) z .d' z | .c' z\"_cresc.\" (c'^a b) z .d' z | %23",
" .c' z (c'^a b) z .d' z |!ff! .f'2 .f'.f' .f'2 .f'.f' | .f'2 .f.f .f2 .f.f | %26",
" .f z\"_dim.\" .f.^e .f z .f.e | .f z .f.^e .f z z2 |] %28",
"V:2",
" [D,A,]/[D,A,]/[D,A,]/ z/ [D,A,]/[D,A,]/[D,A,]/ z/ | .D .C (B,3/2 .A,/) | [^G,DE] z z .[E,B,D] | %3",
" [A,C] z z2 | D, [F,A,D] D, [F,A,D] | D, [F,A,D] D, [F,A,D] | D, [F,A,D] D, [F,A,D] | %7",
" D, [F,A,D] D, [F,A,D] | E, [B,D] E, [B,D] | A,, [F,A,D] A,, [F,A,D] | [A,,E,G,] z [A,,C,G,] z | %11",
" [D,F,A,] [D,F,A,] [D,F,A,] z | D, [G,B,D] D, [G,B,D] | D, [G,B,D] D, [G,B,D] | %14",
" D, [F,A,D] D, [F,A,D] | D, [F,A,D] D, [F,A,D] | A,, [G,A,C] [G,A,C] [G,A,C] | %17",
" A,, [F,A,D] [F,A,D] [F,A,D] | A,, [G,A,C] [G,A,C] [G,A,C] | D, [F,A,D] [F,A,D] [F,A,D] | %20",
" A,, [G,A,C] [G,A,C] [G,A,C] | D, [F,A,D] [F,A,D] [F,A,D] | [F,^A,C]2 [F,B,D] [F,B,D] | %23",
" [F,^A,C]2 [F,B,D] [F,B,D] | [F,^A,C] [F,B,D] [F,A,C] [F,B,D] | [F,^A,C] [F,B,D] [F,A,C] [F,B,D] | %26",
" [F,^A,C] z [F,A,C] z | [F,^A,C] z [F,A,C] z |] %28",
""];
