media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":80,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":43};
abc_arr = ["X:1",
"T:Satyagraha",
"%%measurenb 0",
"%%score { 1 | ( 2 3 ) }",
"L:1/8",
"Q:1/4=80",
"M:4/4",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:3 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/4",
"V:1",
" [A,F][CA][Fc][Ae] [Fc]AFA | [B,G][EB][Gd][Be] [Gd]BGB | [CA][Ec][Ae][cf] [Ae]cAc | %3",
" Bc[Be][cf] [Be]cBc | [A,F][CA][Fc][Ae] [Fc]AFA | [B,G][DB][Gd][Be] [Gd]BGB | %6",
" [CA][Ec][Ae][cf] [Ae]cAc | [DB][Ec][Be][cf] [Be]c[DB][Ec] |[M:3/4] [A,F][CA] [Fc][Ae] [Fc]A | %9",
" G[DB] [Gd][Be] [Gd]B | [CA][Ec] [Ae][cf] [Ae]c | Bc [Be][cf] [Be]c | [A,F][CA] [Fc][Ae] [Fc]A | %13",
" G[DB] [Gd][Be] [Gd]B | [CA][Ec] [Ae][cf] [Ae]c | Bc [Be][cf] [Be]c | %16",
"[M:4/4] !>!c'a[cf]e [cf]a!>!c'a | !>!c'b[dg]e [dg]b!>!c'b | !>!b[cg]e[cf] e[cg]!>!b[cg] | %19",
" !>!b[cg]ef e[cg]!>!b[cg] |[M:3/4] !>!c'a [Fcf][Ae] [Fcf]a | !>!c'b [Gdg][Be] [Gdg][Bb] | %22",
" !>!b[cg] e[cf] e[cg] | !>!b[cg] e[cf] [Be][cg] | !>!c'a [Fcf][Ae] [Fcf]a | %25",
" !>!c'b [Gdg][Be] [Gdg][Bb] | !>!b[cg] e[cf] e[cg] | !>!b[cg] e[cf] [Be][cg] | %28",
" !>!c'a [Fcf][Ae] [Fcf]a | !>!c'b [Gdg][Be] [Gdg][Bb] | !>!b[cg] e[cf] e[cg] | %31",
" !>!b[cg] e[cf] [Be][cg] |[M:4/4] !>!c'a[cf]e [cf]a!>!c'a | !>!c'b[dg]e [dg]b!>!c'b | %34",
" !>!b[cg]e[cf] e[cg]!>!b[cg] | !>!b[cg]ef e[cg]!>!b[cg]- | [cg]8 |] %37",
"V:2",
"!ped! z2 A,C A,CA,C!ped-up! |!ped! z2 B,D B,DB,D!ped-up! |!ped! z2 CE CECE | DEDE DEDE!ped-up! | %4",
"!ped! z2 A,C A,CA,C!ped-up! |!ped! z2 B,D B,DB,D!ped-up! |!ped! z2 CE CECE | z2 DE DE z2!ped-up! | %8",
"[M:3/4]!ped! !>!F,2 !>!G,C !>!A,C!ped-up! |!ped! !>!B,2 !>!CD !>!D2!ped-up! |!ped! !>!E2 CE CE | %11",
" DE DE DE!ped-up! |!ped! !>!F,2 !>!G,C !>!A,C!ped-up! |!ped! !>!B,2 !>!CD !>!D2!ped-up! | %14",
"!ped! !>!E2 CE CE!ped-up! | DE DE DE | %16",
"[M:4/4]!ped! z[K:treble] C[A,F][CA] [A,F][CA][A,F][CA]!ped-up! | %17",
"!ped! z[K:treble] [B,G][DB][B,G] [DB][B,G][DB][B,G]!ped-up! |!ped! z E[CA]E [CA]E[CA]E | %19",
" [DB]E[DB]E [DB]EDE!ped-up! |[M:3/4][K:bass]!ped! !>!F,C !>!G,2 !>!A,C!ped-up! | %21",
"!ped! !>!B,D !>!C2 !>!D2!ped-up! |!ped! z E [CA]E [CA]E | [DB]E [DB]E DE!ped-up! | %24",
"!ped! !>!F,C !>!G,2 !>!A,C!ped-up! |!ped! !>!B,D !>!C2 !>!D2!ped-up! |!ped! z E [CA]E [CA]E | %27",
" [DB]E [DB]E DE!ped-up! |!ped! !>!F,C !>!G,2 !>!A,C!ped-up! |!ped! !>!B,D !>!C2 !>!D2!ped-up! | %30",
"!ped! z E [CA]E [CA]E | [DB]E [DB]E DE!ped-up! | %32",
"[M:4/4][K:bass]!ped! z[K:treble] C[A,F][CA] [A,F][CA][A,F][CA]!ped-up! | %33",
"!ped! z[K:treble] D[B,G][DB] [B,G][DB][B,G][DB]!ped-up! |!ped! z E[CA]E [CA]E[CA]E!ped-up! | %35",
"!ped! z[K:treble] E[DB]E [DB-]EDE- | [EB]8!ped-up! |] %37",
"V:3",
" C,4 | D,4 | E,4- | E,4 | C,4 | D,4 | E,4 | z3 !>!E, |[M:3/4] C,3 | D,3 | E,3- | E,2 !>!E, | C,3 | %13",
" D,3 | E,3- | E,3 |[M:4/4] C,4[K:treble] | D,4[K:treble] | E,4 | x3 !>!E, |[M:3/4][K:bass] C,3 | %21",
" D,3 | !>!E,3- | E,2 !>!E, | C,3 | D,3 | !>!E,3- | E,2 !>!E, | C,3 | D,3 | !>!E,3- | E,3 | %32",
"[M:4/4][K:bass] !>!C,4[K:treble] | !>!D,4[K:treble] | !>!E,4 | C,3[K:treble] z | x4 |] %37",
""];
