media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"nosound","tempo":90,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":36};
abc_arr = ["X:1",
"T:Prince Sidon (The Legend of Zelda: Breath of the Wild OST)",
"C:Manaka Kataoka, Yasuaki Iwata, and Hajime Wakai",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/4=90",
"M:4/4",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pia.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
" z8 | z8 | z8 | z8 | b8- | b3 c' b3 c' | b8- | bbag a2 d'^c'/=c'/ | b8- | b3 ^f' b3 f' | e'8- | %11",
" e'e'd'e' ^f'2 d'2 | e'8- | e'8 | e8- | e7 d'/^d'/ | e'8- | e'7 g/^f/ | e8- | e8 |] %20",
"V:2",
"!ped! !>!E,G,B,[I:staff -1]B- BEGE!ped-up! | %1",
"!ped![I:staff +1] !>!D,^F,B,[I:staff -1]B- BD^FD!ped-up! | %2",
"!ped![I:staff +1] !>!C,E,G,[I:staff -1]G- GCEC!ped-up! | %3",
"!ped![I:staff +1] !>!B,,^D,^F,[I:staff -1]^F- FB,^DB,!ped-up! | %4",
"!ped![I:staff +1] !>!E,G,B,[I:staff -1]B- BEGE!ped-up! | %5",
"!ped![I:staff +1] !>!D,^F,B,[I:staff -1]B- BD^FD!ped-up! | %6",
"!ped![I:staff +1] !>!C,E,G,[I:staff -1]G- GCEC!ped-up! | %7",
"!ped![I:staff +1] !>!B,,^D,^F,[I:staff -1]^F- FB,^DB,!ped-up! | %8",
"!ped![I:staff +1] !>!E,G,B,[I:staff -1]B- BEGE!ped-up! | %9",
"!ped![I:staff +1] !>!D,^F,B,[I:staff -1]B- BD^FD!ped-up! | %10",
"!ped![I:staff +1] !>!C,E,G,[I:staff -1]G- GCEC!ped-up! | %11",
"!ped![I:staff +1] !>!B,,^D,^F,[I:staff -1]^F- FB,^DB,!ped-up! | %12",
"[I:staff +1][K:treble]!ped! [EAB]B,EA- AE[AB]E!ped-up! |!ped! [E^GB]B,E[GB]- [GB]E[GB]E!ped-up! | %14",
"!ped! [EGB]B,E[GB]- [GB]E[GB]E!ped-up! |!ped! [E^FB]B,E[FB]- [FB]E[FB]E!ped-up! | %16",
"!ped! [EAB]B,E[AB]- [AB]E[AB]E!ped-up! |!ped! [E^GB]B,E[GB]- [GB]E[GB]E!ped-up! | %18",
"!ped! [EGB]B,E[GB]- [GB]E[GB]E!ped-up! |!ped! [B,^FB]2 E [B,^DB]3[K:bass] B,,2!ped-up! |] %20",
""];
