media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":1,"volgmod":"6",
"chkmod":"4","extract":1,"portsel":"synth","tempo":90,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":1,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":2,"line":99,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"],"pw":32};
abc_arr = ["X:1",
"T:Prince Sidon (The Legend of Zelda: Breath of the Wild OST)",
"C:Manaka Kataoka, Yasuaki Iwata, and Hajime Wakai",
"%%measurenb 0",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/4=90",
"M:4/4",
"I:linebreak $",
"K:C",
"V:1 treble nm=\"Piano\" snm=\"Pia.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
" z8 | z8 | z8 | z8 |!8va(! b8- | b3 c' b3 c' | b8- | bbag a2 d'_d'/c'/ | b8- | b3 _g' b3 g' | %10",
" e'8- | e'e'd'e' _g'2 d'2!8va)! | e'8- | e'8 | e8- | e7 d'/^d'/ | e'8- | e'7 g/^f/ | e8- | e8 |] %20",
"V:2",
"!ped! !>!D,G,B, B2 EGE!ped-up! |!ped! !>!D,^F,B, B2 D^FD!ped-up! |!ped! !>!C,E,G, G2 CEC!ped-up! | %3",
"!ped! !>!B,,^D,^F, ^F2 B,^DB,!ped-up! |!ped! !>!E,G,B, B2 EGE!ped-up! | %5",
"!ped! !>!D,^F,B, B2 D^FD!ped-up! |!ped! !>!C,E,G, G2 CEC!ped-up! | %7",
"!ped! !>!B,,^D,^F, ^F2 B,^DB,!ped-up! |!ped! !>!E,G,B, B2 EGE!ped-up! | %9",
"!ped! !>!A,,E,G, B2 ^CEC!ped-up! |!ped! !>!C,G,B, B2 EGE!ped-up! | %11",
"!ped! !>!B,,^F,A, B2 D^FD!ped-up! | %12",
"!ped![I:staff -1] [EAB][I:staff +1]B,E[I:staff -1] A2[I:staff +1] E[I:staff -1][AB][I:staff +1]E!ped-up! | %13",
"!ped![I:staff -1] [E^GB][I:staff +1]B,E[I:staff -1] [GB]2[I:staff +1] E[I:staff -1][GB][I:staff +1]E!ped-up! | %14",
"!ped![I:staff -1] [EGB][I:staff +1]B,E[I:staff -1] [GB]2[I:staff +1] E[I:staff -1][GB][I:staff +1]E!ped-up! | %15",
"!ped![I:staff -1] [E^FB][I:staff +1]B,E[I:staff -1] [FB]2[I:staff +1] E[I:staff -1][FB][I:staff +1]E!ped-up! | %16",
"!ped![I:staff -1] [EAB][I:staff +1]B,E[I:staff -1] [AB]2[I:staff +1] E[I:staff -1][AB][I:staff +1]E!ped-up! | %17",
"!ped![I:staff -1] [E^GB][I:staff +1]B,E[I:staff -1] [GB]2[I:staff +1] E[I:staff -1][GB][I:staff +1]E!ped-up! | %18",
"!ped![I:staff -1] [EGB][I:staff +1]B,E[I:staff -1] [GB]2[I:staff +1] E[I:staff -1][GB][I:staff +1]E!ped-up! | %19",
"!ped! [B,^FB]2 E [B,^DB]3 B,,2!ped-up! |] %20",
""];
