media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":true,"volgmod":"6",
"chkmod":2,"extract":1,"portsel":"synth","tempo":136,"kbopa":0,"scl":1,"gain":5,
"drempel":1,"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":true,
"exact":0,"nolyr":0,"lus":0,"lusstop":1,"lncur":true,"tmng":0,"tmng2":0,"metmrk":0,
"ftyp":0,"nocnt":0,"scal":0,"echo":1,"staff":1,"line":30,"begin":0,"btime":0,"etime":0,
"ctrls":0,"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"]};
abc_arr = ["X:1",
"T:Étude No. 20 in E Major",
"C:Stephen Heller(1815–1888)",
"Z:Heller István",
"%%measurenb 0",
"%%scale 0.83",
"%%pagewidth 21.01cm",
"%%leftmargin 1.00cm",
"%%rightmargin 1.00cm",
"%%score { ( 1 2 ) | 3 }",
"L:1/8",
"Q:1/4=136",
"M:2/4",
"I:linebreak $",
"K:E",
"V:1 treble nm=\"Piano\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:2 treble ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/4",
"V:3 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"\"^Allegro\"!p! z4 | z4 | (E,/G,/B,/E/ .G) z | (!>!!^![FB]2 [B,F]) z | (E,/G,/C/E/ .G) z | %5",
" (!>!!^![Ae]2 [EA]) z |!<(! (D/F/A/B/ d/f/.a)!<)! |$!mp!!>(! (!>!!^![Gdg]2 [Gce]) z!>)! | %8",
"!p! [CEF]2 ([A,DA]>[G,EG]) | [G,EG]3 z | (E,/G,/B,/E/ .G) z | (!>!!^![FB]2 [B,F]) z | %12",
" (E,/G,/C/E/ .G) z | (!>!!^![Ae]2 [EA]) z |$!p!!<(! (D/F/A/B/ d/f/.a)!<)! | %15",
"!mp!!>(! (!>!!^![Gdg]2 [Gce]) z!>)! |!p! [CEF]2 ([A,DA]>[G,EG]) | [G,EG]3 z |!p! z ([=DGB]2 [EGc] | %19",
" e[FA=d]c[=DFB] | A[B,=DG][A,DF]>[G,DE]) |$ (!>!!^![A,CE]2 [CEA]) z | z ([=DGB]2 [EGc] | %23",
" e[FA=d]c[=DFB] | A[B,=DG][A,DF]>[G,DE]) | (!>!!^![A,CE]2 [CEA]) z |!p! (A,/C/E/A/ .c) z/!mf! (d/ | %27",
" [Ee]2 [B,B]) z |$!p! (F,/A,/C/F/ .A) z/!mf! (B/ | !^![Cc]2 [G,G]) z |!p! z ([^B,DG]2 [CEA] | %31",
"!<(! c[DF^B]d[EGc]!<)! |!mp!!>(! e[FAd][EGc]>[DG^B])!>)! |!p! (!>!!^![EGc]2 [EG]) z | %34",
" z ([^B,DG]2 [CEA] |!<(! c[DF^B]d[EGc])!<)! |$!mf! z ([DF=B]2 [E=Gc] |!<(! e[FAd]f[GBe])!<)! | %38",
"!f!!>(! (g[Acf]d[GBe]) | (e[FAd]^B[EGc]) | (c[DF=B])(B[CEA]) | (A[B,DG])(G[A,CF]) | %42",
" (F[G,B,E])(E[F,A,D]) | %43",
"[K:bass][Q:1/4=132]\"^poco riten.\" (D[E,A,C]){/D}(C[Q:1/4=126]\"^126\"[D,A,B,])!>)! |$ %44",
"!pp! ([G,B,]2 [E,G,])[Q:1/4=118]\"^118\" z[Q:1/4=122]\"^122\" |[Q:1/4=136]\"^a tempo\"!<(! z4!<)! | %46",
"[K:treble]!p! (E,/G,/B,/E/ .G) z | (!>!!^![FB]2 [B,F]) z | (E,/G,/C/E/ .G) z | %49",
" (!>!!^![Ae]2 [EA]) z |!<(! (D/F/A/B/ d/f/.a)!<)! |!f!!>(! (!^![Gdg]2 [Gce]) z!>)! |$ %52",
"!p! [CEF]2 ([A,DA]>[G,EG]) | [G,EG]3 z | (E,/G,/B,/E/ .G) z/!mf! ([^A^a]/ | !>!!^![Bb]2 [Ff]) z | %56",
"[K:bass]!p! (=D,/F,/A,/=D/ .F)[K:treble] z/!mf! ([Gg]/ |!<(! !>!!^![Aa]2 [Ee]) z!<)! |$ %58",
"!f! (A,/D/F/A/ d/f/.a) |!>(! (!>!!^![Gdg]2 [Gce]) z!>)! |!p! [CEF]2 ([A,DA]>[G,EG]) | %61",
" [G,EG]2 !>!!^![B,EB]2 |!p! [CEF]2 ([A,DA]>[G,EG]) | [G,EG]2 !>!!^![EBe]2 | %64",
"!p! [CEF]2 ([A,DA]>[G,EG]) | [G,EG]2!f! ([Beg]2 |$ [Acf]2 [FAd]>[EGe]) |!>(! [EGe]3 z!>)! | %68",
"!p! z ([=DGB]2 [EGc] | e[FA=d]c[=DFB] | A[B,=DG][A,DF]>[G,DE]) |$ %71",
"!<(! (!>!!^![A,CE]2 .[A,CA]) z!<)! |!mf! z ([B^df]2 [Beg] |!<(! b[cea]g[Acf]!<)! | %74",
"!f!!>(! e[F=Ad][EAc]>[DAB])!>)! |!mf!!>(! (!>!!^![EGB]2 .[EGe]) z!>)! |$!p! z ([=DGB]2 [EGc] | %77",
" e[FA=d]c[=DFB] | A[B,=DG][A,DF]>[G,DE]) |!<(! (!>!!^![A,CE]2 .[A,CA]) z!<)! | %80",
"!mf! z ([B^df]2 [Beg] |$ b[cea]g[Acf] | e[F=Ad][EAc]>[DAB]) |!>(! (!>!!^![EGB]2 .[A=ce]) z!>)! | %84",
"!p! (A,/=C/E/A/ .=c) z | (!>!!^![EGB]2 .[A=ce]) z |$ (A,/=C/E/A/ .=c) z | %87",
" [EGB]2 (!>!!^![=ce]>[Ac]) | [GB]2 (!>!!^![E=c]>[=CA]) | [B,G]2!p! (A>E) | (G>E) (F>E) |$ %91",
" (G>E) (A>E) | (G>E) (F>E) |\"_sempre \" .[B,G] z (G,/B,/E/F/ | .[B,G]) z (G,/B,/E/F/ |$ %95",
" .[B,G]) z\"_leggiero\" (^A,/B,/A,/B,/) | z2 (^A/B/A/B/) | .g2 z2 | .[Bgb]2 z2 | .[ege']2 z2 |] %100",
"V:2",
" x2 | x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 | %19",
" x2 | x2 |$ x2 | x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | %38",
" x2 | x2 | x2 | x2 | x2 |[K:bass] x2 |$ x2 | x2 |[K:treble] x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | %53",
" x2 | x2 | x2 |[K:bass] x3/2[K:treble] x/ | x2 |$ x2 | x2 | x2 | x2 | x2 | x2 | x2 | x2 |$ x2 | %67",
" x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 |$ %86",
" x2 | x2 | x2 | x =C | B, =C |$ B, =C | B, =C | x2 | x2 |$ x2 | x2 | x2 | x2 | x2 |] %100",
"V:3",
" .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .D,,.B,,.D,,.B,, | .C,,.G,,.C,,.G,, | %5",
" .=C,,.A,,.C,,.A,, | .B,,,.B,,.B,,,.B,, |$ .^B,,,.^B,,.C,,.C, | .A,,,.A,,.=B,,,.=B,, | %9",
" .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .D,,.B,,.D,,.B,, | .C,,.G,,.C,,.G,, | .=C,,.A,,.C,,.A,, |$ %14",
" .B,,,.B,,.B,,,.B,, | .^B,,,.^B,,.C,,.C, | .A,,,.A,,.=B,,,.=B,, | .E,,.B,,.E,,.B,, | %18",
" .E,,.E,.E,,.E, | .E,,.E,.E,,.E, | .E,,.E,.E,,.E, |$ .A,,.E,.A,,.E, | .E,,.E,.E,,.E, | %23",
" .E,,.E,.E,,.E, | .E,,.E,.E,,.E, | .A,,.E,.A,,.E, | .A,,.E,.A,,.E, | .G,,.E,.G,,.E, |$ %28",
" .F,,.C,.F,,.C, | .E,,.C,.E,,.C, | .G,,.G,.G,,.G, | .G,,.G,.G,,.G, | .G,,.G,.G,,.G, | %33",
" .C,.G,.C,.G, | .G,,.G,.G,,.G, | .G,,.G,.C,.G, |$ .=B,,.=B,.B,,.B, | .B,,.B,.B,,.B, | %38",
" (B,,,B,,) (B,,B,) | (B,,,B,,) (B,,B,) | (B,,,B,,) (B,,B,) | (B,,,B,,) z .B,, | z .B,, z .B,, | %43",
" z .B,, z .B,, |$ .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .D,,.B,,.D,,.B,, | %48",
" .C,,.G,,.C,,.G,, | .=C,,.A,,.C,,.A,, | .B,,,.B,,.B,,,.B,, | .^B,,,.^B,,.C,,.C, |$ %52",
" .A,,,.A,,.=B,,,.=B,, | .E,,.B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .D,,.B,,.D,,.B,, | %56",
" .=D,,.A,,.D,,.A,, | .C,,.A,,.C,,.A,, |$ .=C,,.=C,.B,,,.B,, | .^B,,,.^B,,.C,,.C, | %60",
" .A,,,.A,,.=B,,,.=B,, | .C,,.C, .G,,,.G,, | .A,,,.A,,.B,,,.B,, | .C,,.C, .G,,,.G,, | %64",
" .A,,,.A,,.^B,,,.^B,, | (C,,C, G,,,G,, |$ A,,,A,,=B,,,=B,,) | (E,,/E,/D,/E,/) (E,,/E,/D,/E,/) | %68",
" (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) | (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) | %70",
" (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) |$ (A,,/E,/D,/E,/) (A,,/E,/D,/E,/) | %72",
" (A,,/A,/G,/A,/) (G,,/G,/^^F,/G,/) | (F,,/F,/^E,/^F,/) (A,,/A,/G,/A,/) | %74",
" (B,,/B,/^A,/B,/) (B,,/B,/A,/B,/) | (E,/B,/^A,/B,/) (E,/B,/A,/B,/) |$ %76",
" (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) | (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) | %78",
" (E,,/E,/^D,/E,/) (E,,/E,/D,/E,/) | (A,,/E,/D,/E,/) (A,,/E,/D,/E,/) | %80",
" (A,,/A,/G,/A,/) (G,,/G,/^^F,/G,/) |$ (F,,/F,/^E,/^F,/) (A,,/A,/G,/A,/) | %82",
" (B,,/B,/^A,/B,/) (B,,/B,/A,/B,/) | (E,,/E,/D,/E,/) (=A,,/E,/D,/E,/) | %84",
" (A,,/E,/D,/E,/) (A,,/E,/D,/E,/) | (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) |$ %86",
" (A,,/E,/D,/E,/) (A,,/E,/D,/E,/) | (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) | %88",
" (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) | (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) | %90",
" (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) |$ (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) | %92",
" (E,,/E,/D,/E,/) (A,,/E,/D,/E,/) | (E,,/E,/D,/E,/) z2 | (E,,/E,/D,/E,/) z2 |$ (E,,/E,/D,/E,/) z2 | %96",
" (D/E/D/E/) z2 | z!p! .B,,.E,,.B,, | .E,,.B,,.E,,.B,, | .E,,2 z2 |] %100",
""];
