media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":true,"volgmod":"6",
"chkmod":2,"extract":1,"portsel":"synth","tempo":72,"kbopa":0,"scl":1,"gain":5,"drempel":1,
"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":true,"exact":0,
"nolyr":0,"lus":0,"lusstop":1,"lncur":true,"tmng":0,"tmng2":0,"metmrk":0,"ftyp":0,
"nocnt":0,"scal":0,"echo":1,"staff":1,"line":30,"begin":0,"btime":0,"etime":0,"ctrls":0,
"shrnk":0,"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,
"pnlkrt":0.5,"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,
"stopat":-1,"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66",
"#fc0","#cc0","#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00",
"#ff0","#f00","#0bb","#f00","#aaa","#f00"]};
abc_arr = ["X:1",
"T:Inkwell Isle",
"C:Kris Maddigan",
"Z:Studio MDHR(2017), Comp.: Kris Maddigan, Arr.: James Lambariello, Edit: Vincent Schönbach(2018-04-06)",
"%%measurenb 0",
"%%scale 0.83",
"%%pagewidth 21.59cm",
"%%leftmargin 1.00cm",
"%%rightmargin 1.00cm",
"%%score { 1 | 2 }",
"L:1/8",
"Q:1/4=90",
"M:2/4",
"I:linebreak $",
"K:G",
"V:1 treble nm=\"Piano\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/16",
"V:2 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"!mf! d=f2_e g2>g2 | d=f2_B- B2 z2 | GA_B_e- ee^c2 | d2!f!!>![dd']2 !>![cc']2!mf!!>![Aa]2 ||$ %4",
" [Bb][dd']2[cc'] [ee']2>[ff']2 | [dd'][^c^c']2[dd']- [dd']GF^E | EFGF GA2D- | D^CDE DFcA |$ %8",
" [Bb][dd']2[cc'] [ee']2>[ff']2 | [gg'][ff'][ee'][dd']- [dd']^c=cB | A^c2A cBAc | dc2e dcA^A |$ %12",
" [Bb][dd']2[cc'] [ee']2>[ff']2 | [dd'][^c^c']2[dd']- [dd']GF^E | EFGF GA2B- | Bdc^c d=cEF |$ %16",
" G^E=ED EF^GE | AB2^c- ced2 | G4 z4 | z8 ||$!mp! bd'2c' e'2>f'2 | d'^c'2d'- d'gf^e | efgf ga2d- | %23",
" d^cde dfc'a |$ bd'2c' e'2>f'2 | g'f'e'd'- d'^c'=c'b | a^c'2a c'bac' | d'c'2e' d'c'a^a |$ %28",
" bd'2c' e'2>f'2 | d'^c'2d'- d'gf^e | efgf ga2b- | bd'c'^c' d'=c'ef |$!mf! g^e=ed ef^ge | %33",
" ab2^c'- c'e'd'2 | g4 z4 | z8 ||$!8va(! z d'e'd' e'f'2e'- | e'd'2c'- c'bag | z d'e'd' e'g'2f'- | %39",
" f'e'2d'- d'e'f'g' |$ a'a'^g'a'- a'a'^a'b'- | b'b'^a'b'- b'b'c''^c'' | d''c'' z b' z a' z g' | %43",
" z f' z e' z ^e' z f' |$ z d'e'd' e'f'2e'- | e'd'2c'- c'bag | z d'e'd' e'g'2f'- | %47",
" f'e'2d'- d'e'f'g' |$ a'a'^g'a'- a'a'^a'b'- | b'g'e'd'- d'^c'd'^d' | e'e'2d' f'e'd'g'- | %51",
" g'4 z4!8va)! ||$ z [dd'][ee'][dd'] [ee'][ff']2[ee']- | [ee'][dd']2[cc']- [cc'][Bb][Aa][Gg] | %54",
" z [dd'][ee'][dd'] [ee'][gg']2[ff']- | [ff'][ee']2[dd']- [dd'][ee'][ff'][gg'] |$ %56",
"!8va(! [aa'][aa'][^g^g'][aa']- [aa'][aa'][^a^a'][bb']- | %57",
" [bb'][bb'][^a^a'][bb']- [bb'][bb'][c'c''][^c'^c''] | [d'd''][c'c''] z [bb'] z [aa'] z [gg'] | %59",
" z [ff'] z [ee'] z [^e^e'] z [ff']!8va)! |$ z [dd'][ee'][dd'] [ee'][ff']2[ee']- | %61",
" [ee'][dd']2[cc']- [cc'][Bb][Aa][Gg] | z [dd'][ee'][dd'] [ee'][gg']2[ff']- | %63",
" [ff'][ee']2[dd']- [dd'][ee'][ff'][gg'] |$!8va(! [aa'][aa'][^g^g'][aa']- [aa'][aa'][^a^a'][bb']- | %65",
" [bb']!8va)![gg'][ee'][dd']- [dd'][^c^c'][dd'][^d^d'] | [ee'][ee']2[dd'] [ff'][ee'][dd'][gg']- | %67",
" [gg']4 z4 ||$ [Bb][dd']2[cc'] [ee']2>[ff']2 | [dd'][^c^c']2[dd']- [dd']GF^E | EFGF GA2D- | %71",
" D^CDE DFcA |$ [Bb][dd']2[cc'] [ee']2>[ff']2 | [gg'][ff'][ee'][dd']- [dd']^c=cB | A^c2A cBAc | %75",
" dc2e dcA^A |$ [Bb][dd']2[cc'] [ee']2>[ff']2 | [dd'][^c^c']2[dd']- [dd']GF^E | EFGF GA2B- | %79",
" Bdc^c d=cEF |$!f! G^E=ED EF^GE | AB2^c- ced2 | G4 z4 | z8 ||$ [dgb][dgb]2[dg_b] [dga]2[d_a][Bg]- | %85",
" [Bg][Bf][B=f][Be] [G_B_e]2<[GBe]2 | [FAd][FAd]2_d [FAc]BAG | [FA]2{/^c}.[Ad]2 !>!D4 ||$ %88",
" BdeB [Gg][Gg]Bd | eB[Gg][Gg] BdeB- | BdeB [Ff][Ff] z [Ee]- | [Ee]2Bd [Ee][Ee] z [Ff] |$ %92",
" z [Ff][Aa][Aa] [Dd][^C^c] z [Dd]- | [Dd]2[Ff][Ff] [Aa][Aa] z [Ee]- | %94",
" [Ee][Ee][Gg][Gg] [B,B][^A,^A] z [B,B]- | [B,B]4 z4 |$ BdeB [Gg][Gg]Bd | eB[Gg][Gg] BdeB- | %98",
" BdeB [Ff][Ff] z [Ee]- | [Ee]2Bd [Ee][Ee] z [Ff] |$ z [Ff][Aa][Aa] [Dd][^C^c] z [Dd]- | %101",
" [Dd]2[Ff][Ff] [Aa][Aa] z [Ee]- | [Ee][Ee][Gg][Gg] [B,B][^A,^A] z [B,B]- | [B,B]4 z4 ||$ %104",
" [Bb][dd'][ee'][Bb] [gg'][gg'][Bb][dd'] | [ee'][Bb][gg'][gg'] [Bb][dd'][ee'][Bb]- | %106",
" [Bb][dd'][ee'][Bb] [ff'][ff'] z [ee']- | [ee']2[Bb][dd'] [ee'][ee'] z [ff'] |$ %108",
" z [ff'][aa'][aa'] [dd'][^c^c'] z [dd']- | [dd']2[ff'][ff'] [aa'][aa'] z [ee']- | %110",
" [ee'][ee'][gg'][gg'] [Bb][^A^a] z [Bb]- | [Bb]4 z4 |$ [Bb][dd'][ee'][Bb] [gg'][gg'][Bb][dd'] | %113",
" [ee'][Bb][gg'][gg'] [Bb][dd'][ee'][Bb]- | [Bb][dd'][ee'][Bb] [ff'][ff'] z [ee']- | %115",
" [ee']2[Bb][dd'] [ee'][ee'] z [ff'] |$ z [ff'][aa'][aa'] [dd'][^c^c'] z [dd']- | %117",
" [dd']2[ff'][ff'] [aa'][aa'] z [ee']- | [ee'][ee'][gg'][gg'] [Bb][^A^a] z [Bb]- | [Bb]4 z4 ||$ %120",
" bd'2c' e'2>f'2 | d'^c'2d'- d'gf^e | efgf ga2d- | d^cde dfc'a |$ bd'2c' e'2>f'2 | %125",
" g'f'e'd'- d'^c'=c'b | a^c'2a c'bac' | d'c'2e' d'c'a^a |$ [Bb][dd']2[cc'] [ee']2>[ff']2 | %129",
" [dd'][^c^c']2[dd']- [dd']GF^E | EFGF GA2B- | Bdc^c d=cEF |$ G^E=ED EF^GE | AB2^c- ced2 | %134",
"!mp! z b-b2 c'2^c'2 | d'2g'g z2!8va(! g''2!8va)! |] %136",
"V:2",
" D/=F_E/ G>G | D/=F_B,/- B,/!<(!_B,,/A,,/_A,,/!<)! |!f! G,,/A,,/_B,,/_E,/- E,/E,/^C, | %3",
" D,!>(!!>![D,,D,] !>![E,,E,]!>![F,,F,]!>)! ||$!mf! [G,,G,][G,B,] [D,,D,][G,B,] | %5",
" [G,,G,][G,B,] [B,,B,][B,D] | [C,C][G,,G,] [A,,A,][^A,,^A,] | [B,,B,][D,D] [C,C]!>![C,D,F,] |$ %8",
" [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,]!>![^G,,^G,] | [A,,A,][G,A,^C] [E,E][G,A,C] | %11",
" [D,D][A,CD] [E,E][F,A,CD] |$ [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | %14",
" [C,C][G,,G,] [A,,A,][^A,,^A,] |!<(! [B,,B,][D,D] [C,C][F,A,]!<)! |$ %16",
"!f! [G,,G,][G,B,] [E,,E,][D,E,^G,] | [A,,A,][G,A,^C] [D,,D,][F,A,=C] | [G,,G,][B,D] [C,C][B,D] | %19",
"!>(! [G,,G,]!>![D,,D,] !>![E,,E,]!>![F,,F,]!>)! ||$ [G,,G,][G,B,] [D,,D,][G,B,] | %21",
" [G,,G,][G,B,] [B,,B,][B,D] | [C,C][G,,G,] [A,,A,][^A,,^A,] | [B,,B,][D,D] [C,C]!>![C,D,F,] |$ %24",
" [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,]!>![^G,,^G,] | [A,,A,][G,A,^C] [E,E][G,A,C] | %27",
" [D,D][A,CD] [E,E][F,A,CD] |$ [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | %30",
" [C,C][G,,G,] [A,,A,][^A,,^A,] |!<(! [B,,B,][D,D] [C,C]!>![F,A,]!<)! |$ %32",
" [G,,G,][G,B,] [E,,E,][D,E,^G,] | [A,,A,][G,A,^C] [D,,D,][F,A,=C] |!mp! [G,,G,][B,D] [D,D][B,D] | %35",
" [G,,G,]!>![D,,D,] !>![E,,E,]!>![^E,,^E,] ||$ [F,,F,][A,CD] D,[A,CD] | A,[A,CDF] [A,,A,][A,CDF] | %38",
" [G,,G,][B,DG] D,[B,DG] | G,[B,DG] G,[_B,DE] |$ A,[DFA] D,[DFA] | B,[DGB] B,[DGB] | %42",
" D[FAd] A,[DFA] | G,!>![F,F] !>![E,E]!>![^E,^E] |$ F,[A,CD] D,[A,CD] | F,[A,CD] A,[A,CD] | %46",
" G,[B,DG] D,[B,DG] | G,[B,DG] G,[_B,DE] |$ A,[DFA] D,[DFA] | B,[DGB] E,^G, | A,[CDFA] D,[CDF] | %51",
" [B,DG]!<(! !>![D,,D,] !>![E,,E,]!>![^E,,^E,]!<)! ||$!f! [F,,F,][A,CD] [D,,D,][A,CD] | %53",
" [F,,,F,,][A,CDF] [A,,,A,,][A,CDF] | [G,,,G,,][B,DG] [D,,D,][B,DG] | %55",
" [G,,G,][B,DG] [G,,G,]!>![_B,DE] |$ [A,,,A,,][DFA] [D,,,D,,][DFA] | %57",
" [B,,,,B,,,][DGB] [B,,,,B,,,][DGB] | [D,,,D,,][FAd] [A,,,,A,,,][DFA] | %59",
" [G,,G,]!>![F,,F,] !>![E,,E,]!>![^E,,^E,] |$ [F,,F,][A,CD] [D,,D,][A,CD] | %61",
" [F,,,F,,][A,CDF] [A,,,A,,][A,CDF] | [G,,,G,,][B,DG] [D,,D,][B,DG] | %63",
" [G,,G,][B,DG] [G,,,G,,]!>![_B,DE] |$ [A,,,A,,][DFA] [D,,,D,,][DFA] | %65",
" [B,,,B,,][DGB] [E,,,E,,][^G,,,^G,,] | [A,,,A,,][CDFA] [D,,,D,,][CDF] | %67",
" [B,DG]!>![D,,D,] !>![G,,G,]2 ||$!mf! [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | %70",
" [C,C][G,,G,] [A,,A,][^A,,^A,] | [B,,B,][D,D] [C,C]!>![C,D,F,] |$ [G,,G,][G,B,] [D,,D,][G,B,] | %73",
" [G,,G,][G,B,] [B,,B,]!>![^G,,^G,] | [A,,A,][G,A,^C] [E,E][G,A,C] | [D,D][A,CD] [E,E][F,A,CD] |$ %76",
" [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | [C,C][G,,G,] [A,,A,][^A,,^A,] | %79",
"!<(! [B,,B,][D,D] [C,C][F,A,]!<)! |$ [G,,G,][G,B,] [E,,E,][D,E,^G,] | %81",
" [A,,A,][G,A,^C] [D,,D,][F,A,=C] | [G,,G,][B,D] [D,,D,][B,D] | [G,,G,]!>![D,,D,] !>![G,,G,]2 ||$ %84",
"!f! [G,,,G,,][^G,,,^G,,] [A,,,A,,][^A,,,^A,,] | [B,,,B,,][C,,C,] !>![_E,,_E,]2 | %86",
" [D,,D,][_D,,_D,] [C,,C,][B,,,B,,] | [A,,,A,,][D,,D,] !>![D,,,D,,]2 ||$ %88",
" [G,,G,][D,G,B,] [D,,D,][D,G,B,] | [G,,G,][D,G,B,] [D,,D,][D,G,B,] | %90",
" [E,,E,][E,^G,B,] [B,,,B,,][E,G,B,] | [E,,E,][E,^G,B,] [B,,,B,,][E,G,B,] |$ %92",
" [D,,D,][D,F,A,] [A,,,A,,][D,F,A,] | [D,,D,][D,F,A,] [A,,,A,,][D,F,A,] | %94",
" [G,,G,][D,G,B,] [D,,D,][D,G,B,] | [G,,G,][G,,G,]/[G,,G,]/- [G,,G,]/[A,,A,]/[G,,G,] |$ %96",
" [G,,G,][D,G,B,] [D,,D,][D,G,B,] | [G,,G,][D,G,B,] [D,,D,][D,G,B,] | %98",
" [E,,E,][E,^G,B,] [B,,,B,,][E,G,B,] | [E,,E,][E,^G,B,] [B,,,B,,][E,G,B,] |$ %100",
" [D,,D,][D,F,A,] [A,,,A,,][D,F,A,] | [D,,D,][D,F,A,] [A,,,A,,][D,F,A,] | %102",
" [G,,G,][D,G,B,] [D,,D,][D,G,B,] | [G,,G,]!>![D,,D,] !>![E,,E,]!>![F,,F,] ||$ %104",
" [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] | [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] | %106",
" [E,,,E,,][E,^G,B,] [B,,,,B,,,][E,G,B,] | [E,,,E,,][E,^G,B,] [B,,,,B,,,][E,G,B,] |$ %108",
" [D,,,D,,][D,F,A,] [A,,,,A,,,][D,F,A,] | [D,,,D,,][D,F,A,] [A,,,,A,,,][D,F,A,] | %110",
" [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] | %111",
" [G,,,G,,][G,,,G,,]/[G,,,G,,]/- [G,,,G,,]/[A,,,A,,]/[G,,,G,,] |$ %112",
" [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] | [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] | %114",
" [E,,,E,,][E,^G,B,] [B,,,,B,,,][E,G,B,] | [E,,,E,,][E,^G,B,] [B,,,,B,,,][E,G,B,] |$ %116",
" [D,,,D,,][D,F,A,] [A,,,,A,,,][D,F,A,] | [D,,,D,,][D,F,A,] [A,,,,A,,,][D,F,A,] | %118",
" [G,,,G,,][D,G,B,] [D,,,D,,][D,G,B,] |!>(! [G,,,G,,]!>![D,,,D,,] !>![E,,,E,,]!>![F,,,F,,]!>)! ||$ %120",
" [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | [C,C][G,,G,] [A,,A,][^A,,^A,] | %123",
" [B,,B,][D,D] [C,C]!>![C,D,F,] |$ [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,]!>![^G,,^G,] | %126",
" [A,,A,][G,A,^C] [E,E][G,A,C] |!<(! [D,D][A,CD] [E,E][F,A,CD]!<)! |$ %128",
"!f! [G,,G,][G,B,] [D,,D,][G,B,] | [G,,G,][G,B,] [B,,B,][B,D] | [C,C][G,,G,] [A,,A,][^A,,^A,] | %131",
" [B,,B,][D,D] [C,C][F,A,] |$ [G,,G,][G,B,] [E,,E,][D,E,^G,] | [A,,A,][G,A,^C] [D,,D,][F,A,=C] | %134",
" z/ G,,/-G,, D,,2 | G,,D,,/G,,,/ z2 |] %136",
""];
