media_file = "";
pre_opt = {"delay":1,"eenvoor":0,"metro":1,"keys":0,"mark":0,"mute":true,"volgmod":"6",
"chkmod":4,"extract":1,"portsel":"synth","tempo":70,"kbopa":0,"scl":1,"gain":5,"drempel":1,
"minlev":-18,"bass":0,"mtpo":20,"hrz":0,"vol":50,"nocur":0,"rstmute":true,"exact":0,
"nolyr":0,"lus":0,"lusstop":1,"lncur":1,"tmng":0,"tmng2":0,"metmrk":0,"ftyp":0,"nocnt":0,
"scal":0,"echo":1,"staff":1,"line":99,"begin":0,"btime":0,"etime":0,"ctrls":0,"shrnk":0,
"lat":0,"pnlerr":0.5,"pnltim":0.5,"oneclr":0,"late1":150,"late2":1000,"pnlkrt":0.5,
"kort":30,"minkort":200,"atagTijd":-1,"btagTijd":-1,"audOn":true,"hide2cur":0,"stopat":-1,
"hinfo":36,"mat":0.5,"tmo":200,"kleur":["#f9f","#3cf","#c99","#f66","#fc0","#cc0",
"#ccc"],"ntGoed":"#080","ntFout":"#f00","ntWacht":"#0dd","ntKleur":["#f00","#ff0",
"#f00","#0bb","#f00","#aaa","#f00"],"pw":60};
abc_arr = ["X:1",
"T:Mazurka in F minor",
"C:Frédéric Chopin",
"%%measurenb 0",
"%%score { ( 1 2 ) | ( 3 4 ) }",
"L:1/4",
"Q:1/4=70",
"M:3/4",
"I:linebreak $",
"K:Ab",
"V:1 treble nm=\"Pianinas\" snm=\"Pno.\"",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"L:1/8",
"V:2 treble ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:3 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:4 bass ",
"%%MIDI channel 1",
"%%MIDI program 0",
"%%MIDI control 7 100.000054",
"%%MIDI control 10 63.5",
"V:1",
"!p!\"^Lento ma non troppo\" c2- cd dc | =B^A B2 g2 | _B2- Bc cB | =A^G A2 f2 | _A2- A_B BA | %5",
" G^F G2 d2 | c2 cBAG | BAFGA=B | c2- cd=Bd | c^A =B_agB | _B2- Bc cB | B^G =A_gfA | _A2- A_cBA | %13",
" A2- ^G=A^A=B | ^c=d^d=e=a^g | ^f=e=d^G=A=B | ^c=d^d=e=a^g | ^f=e=d^G=A=B | d2 =Bc=f=e | %19",
" _e=d_d=EFG | AB=Bcf=e | _e=d_d=EFG | F4 GA | B4 cG | ACEA=Bc | =d2 egf=B | c6 | =d4 e=B | %28",
" c2 =Bc=de | f2 =efga | g6- | g2 ^fg=b=a | =d2 =f4- | f2 =ef=ag | c2 _e4- | e2 =degf | B2 _d4 | %37",
" =A2 c4 | ^G2 =B4 | [Fc-]2 cd dc | P=B^A B2 g2 | _B2- Bc cB | P=A^G A2 f2 | _A2- A_B BA | %44",
" G^F G2 d2 | c2 cBAG | BAFGA=B | c2- cd=Bd | c^A =B_agB | _B2- Bc cB | B^G =A_gfA | _A2- A_cBA | %52",
" A2- ^G=A^A=B | ^c=d^d=e=a^g | ^f=e=d^G=A=B | ^c=d^d=e=a^g | ^f=e=d^G=A=B | d2 =Bc=f=e | %58",
" _e=d_d=EFG | AB=Bcf=e | _e=d_d=EF{/A}G | F=E F2 ||[K:F] [_EA]2 | [B,FB]2 [=B,E^G]2 [^CEA]2 | %64",
" [CD^F]2 G3 =F | =E3 [Bd]E[Bd] | E[Bd] [Fc]2 [Ff]2 | [B,FB]2 [_D_EG]2 [CE_A]2 | [_C_DF]2 _G3 F | %69",
" FEPDCAE | F2 d_dc_c | [B,FB]2 [=B,E^G]2 [^CEA]2 | [CD^F]2 G3 =F | =E3 [Bd]E[Bd] | %74",
" [B,E][Bd] c2 [FBf]2 | [_DGB]2 [B,=DG]2 [_CF_A]2 | [DF]2 [D^F]3 [D=F] | FEPDCAE | F2 z2 c2 || %79",
"[K:Ab] c2- cd dc | =B^A B2 g2 | _B2- Bc cB | =A^G A2 f2 | _A2- A_B BA | G^F G2 d2 | c2 cBAG | %86",
" BAFGA=B | c2- cd=Bd | c^A =B_agB | _B2- Bc cB | B^G =A_gfA | _A2- A_cBA | A2- ^G=A^A=B | %93",
" ^c=d^d=e=a^g | ^f=e=d^G=A=B | ^c=d^d=e=a^g | ^f=e=d^G=A=B | d2 =Bc=f=e | _e=d_d=EFG | AB=Bcf=e | %100",
" _e=d_d=EFG | F=E F4 |] %102",
"V:2",
" x3 | x3 | x3 | x3 | x3 | x3 | z =E E | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | %19",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x2 c- | c/=B/=e/^d/=d/^c/ | =c c c | %32",
" c =B/c/=e/=d/ | _B B B | B =A/B/=d/c/ | _A A A | A G/^F/ G- | G ^F/^E/ F- | F =F/=E/ F | x3 | x3 | %41",
" x3 | x3 | x3 | x3 | z =E E | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | %60",
" x3 | x2 ||[K:F] x | x3 | x [_B,D] x | B,3 | x3 | x3 | x [B,_D] x | [G,B,] x2 | x3 | x3 | %72",
" x [_B,D] x | B,3 | x3 | x3 |[I:staff +1] ^G, A,3/2 _A,/ | [=G,B,] x2 | x3 ||[K:Ab] x3 | x3 | x3 | %82",
" x3 | x3 | x3 |[I:staff -1] z =E E | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | %98",
" x3 | x3 | x3 | x3 |] %102",
"V:3",
" z [A,CF] [A,CF] | z [G,=DF] [G,_DF] | z [_G,_D_F] [G,CE] | z [F,CE] [F,_CE] | %4",
" z [F,=B,=D] [=E,B,D] | z [=E,_B,_D] [F,B,F] | z [G,B,C] [C,B,] | z F,, [F,A,D] | %8",
" z [F,A,C] [A,CF] | z [G,=DF] [G,_DF] | z [_G,_D_F] [G,CE] | z [F,CE] [F,_CE] | %12",
" z [F,_C=D] [_F,CD] | z [=F,B,=D] [=E,^G,D] | =A,, [=E,^C] z | =A,, [^F,=A,=D] [=E,^G,D] | %16",
" =A,, [=E,^C] [E,^C] | =A,, [^F,=D] [=E,D] | =A,, z [=F,=C] | _B,, [F,_D] [C,=E,_B,] | %20",
" F,, [C,A,] z | z F,, [D,A,] | F,, [C,A,] _C,/B,,/ | E,, [E,G,D] [E,D] | A,, [E,C] [=D,F,C] | %25",
" G,, [G,F] [G,=DF] | C, [G,CE] G | G,, [G,=B,F] [G,F] | .C, [G,E] z | .A,, [A,CF] .=D,, | G,, z z | %31",
"[K:treble] z [=D=A] [D^F] | z =D/=E/G/=F/ | _D [CF] =E | z C/=D/F/E/ | _C [B,E] [B,=D] | %36",
"[K:bass] z [_F,B,]/E,/ [E,B,] | [E,C] [_E,=A,]/=D,/ [D,-A,] | [D,=B,] [_D,_A,] [_D,A,] | %39",
" [C,A,] [G,=E] [A,CF] | C, [G,=DF] [G,_DF] | C, [_G,C=E] [G,C_E] | C, [F,CE] [F,_CE] | %43",
" C, [F,=B,=D] [=E,B,D] | C, [=E,_B,_D] [F,B,F] | z [G,B,C] [C,B,] | z F,, [F,A,D] | %47",
" z [F,A,C] [A,CF] | z [G,=DF] [G,_DF] | z [=G,_D_F] [_G,DF] | z [F,CE] [F,_CE] | %51",
" z [F,_C__E] [_F,CE] | z [=F,B,=D] [=E,^G,D] | =A,, [=E,^C] z | =A,, [^F,=A,=D] [=E,^G,D] | %55",
" =A,, [=E,^C] [E,^C] | =A,, [^F,=D] [=E,D] | =A,, z [=F,=C] | _B,, [F,_D] [C,=E,_B,] | %59",
" F,, [C,A,] z | z [D,A,] [C,B,] | F,, [C,A,] ||[K:F] F, | D, E, A,, | [D,A,] G,, _D, | %65",
" z [G,C] [G,C] |[I:staff -1] B,[I:staff +1] A,2 | _D, _E, _A,, | [_D,_A,] _G,, D, | %69",
" C,, [C,E,B,] [C,G,B,] | F,, z [F,A,_E] | D, E, A,, | [D,A,] G,, _D, | C, [G,C] [G,C] | %74",
" F,, F, [D,B,] | _E, D, _D, | =B,, A,, D,,/=B,,,/ | C,, [C,E,B,] [C,G,B,] | F,, [C,A,] z || %79",
"[K:Ab] z [A,CF] [A,CF] | z [G,=DF] [G,_DF] | z [_G,_D_F] [G,CE] | z [F,CE] [F,_CE] | %83",
" z [F,=B,=D] [=E,B,D] | z [=E,_B,_D] [F,B,F] | z [G,B,C] [C,B,] | z F,, [F,A,D] | %87",
" z [F,A,C] [A,CF] | z [G,=DF] [G,_DF] | z [=G,_D_F] [_G,CE] | z [F,CE] [F,_CE] | %91",
" z [F,_C__E] [_F,CE] | z [=F,B,=D] [=E,^G,D] | =A,, [=E,^C] z | =A,, [^F,=A,=D] [=E,^G,D] | %95",
" =A,, [=E,^C] [E,^C] | =A,, [^F,=D] [=E,D] | =A,, z [=F,=C] | _B,, [F,_D] [C,=E,_B,] | %99",
" F,, [C,A,] z | z [D,A,] [C,B,] | F,, [C,A,]2 |] %102",
"V:4",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | %19",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x2 [G,CE] | x3 | x3 | x3 | x3 |[K:treble] x3 | x G, G, | x3 | %34",
" x F, F, | x3 |[K:bass] x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | %51",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x2 ||[K:F] x | x3 | x3 | C,2 z | F,, x _E, | %67",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 ||[K:Ab] x3 | x3 | x3 | x3 | x3 | x3 | %85",
" x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 | x3 |] %102",
""];
